typography_spectrum: 0.2024704
color:
  saturation: 0.7590201
  brandStrength: 0.8125
  lightness: 0.2583244
  brandColors:
    - '#EEF5EE'
    - '#1879BD'
    - '#101B4D'
    - '#1DA8E9'
    - '#87C7E3'
  rhythmicContrast: 0.4860365
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.255102
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Richard Pochop
  email: richard@eyephotou.com
  url: www.eyephotou.com
name: Ifotou
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: my Photolife
description: all I want to do...
purpose: []
